In [16]:
from multiple_linear_regression import MultipleLinearRegression
import pandas as pd
import numpy as np

In [17]:
data = pd.read_csv('Life Expectancy Data.csv.xls', sep=",")
data.columns

Index(['Country', 'Year', 'Status', 'Life expectancy ', 'Adult Mortality',
       'infant deaths', 'Alcohol', 'percentage expenditure', 'Hepatitis B',
       'Measles ', ' BMI ', 'under-five deaths ', 'Polio', 'Total expenditure',
       'Diphtheria ', ' HIV/AIDS', 'GDP', 'Population',
       ' thinness  1-19 years', ' thinness 5-9 years',
       'Income composition of resources', 'Schooling'],
      dtype='object')

In [18]:
data = data.dropna()

In [19]:
x = np.array(data[
    [
        'Adult Mortality',
        'infant deaths',
        'percentage expenditure',
        'Alcohol',
        'GDP',
        'Total expenditure'
     ]
]
)
x.shape

(1649, 6)

In [20]:
y = np.array(data['Life expectancy '])
y.shape

(1649,)

In [21]:
x.T

array([[2.63000000e+02, 2.71000000e+02, 2.68000000e+02, ...,
        7.30000000e+01, 6.86000000e+02, 6.65000000e+02],
       [6.20000000e+01, 6.40000000e+01, 6.60000000e+01, ...,
        2.50000000e+01, 2.50000000e+01, 2.40000000e+01],
       [7.12796236e+01, 7.35235817e+01, 7.32192427e+01, ...,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00],
       [1.00000000e-02, 1.00000000e-02, 1.00000000e-02, ...,
        4.43000000e+00, 1.72000000e+00, 1.68000000e+00],
       [5.84259210e+02, 6.12696514e+02, 6.31744976e+02, ...,
        5.73483400e+01, 5.48587312e+02, 5.47358878e+02],
       [8.16000000e+00, 8.18000000e+00, 8.13000000e+00, ...,
        6.53000000e+00, 6.16000000e+00, 7.10000000e+00]])

In [22]:
model = MultipleLinearRegression()
model.train(x, y)

In [25]:
arr = [
    [4, 10],
    [3, 30]
]
arr = np.array(arr).astype(np.float64)

In [28]:
np.insert(arr, 0, np.array([1.0, 1.0]), axis=1).T

array([[ 1.,  1.],
       [ 4.,  3.],
       [10., 30.]])

In [10]:
model.get_weights()

array([[ 7.32407122e+01],
       [-4.30990313e-02],
       [-7.20990573e-03],
       [-4.89857905e-04],
       [ 4.26850252e-01],
       [ 2.11700499e-04],
       [ 1.30169989e-01]])

In [11]:
model.get_features()

array([[1.00000000e+00, 2.63000000e+02, 6.20000000e+01, ...,
        1.00000000e-02, 5.84259210e+02, 8.16000000e+00],
       [1.00000000e+00, 2.71000000e+02, 6.40000000e+01, ...,
        1.00000000e-02, 6.12696514e+02, 8.18000000e+00],
       [1.00000000e+00, 2.68000000e+02, 6.60000000e+01, ...,
        1.00000000e-02, 6.31744976e+02, 8.13000000e+00],
       ...,
       [1.00000000e+00, 7.30000000e+01, 2.50000000e+01, ...,
        4.43000000e+00, 5.73483400e+01, 6.53000000e+00],
       [1.00000000e+00, 6.86000000e+02, 2.50000000e+01, ...,
        1.72000000e+00, 5.48587312e+02, 6.16000000e+00],
       [1.00000000e+00, 6.65000000e+02, 2.40000000e+01, ...,
        1.68000000e+00, 5.47358878e+02, 7.10000000e+00]])

In [12]:
model.evaluate(x, y)

42126615.0450344